services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./index/place-index.json:/usr/share/elasticsearch/place-index.json
      - ./index/synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt
      - ./init-index.sh:/usr/share/elasticsearch/init-index.sh
    ports:
      - "9200:9200"
    command: >
      /bin/bash -c "
      chmod +x /usr/share/elasticsearch/init-index.sh &&
      /usr/share/elasticsearch/init-index.sh &
      exec /usr/local/bin/docker-entrypoint.sh
      "
    healthcheck:
      test: [ "CMD", "curl", "-s", "-XGET", "http://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

volumes:
  esdata:
    driver: local