version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./index/place-index.json:/usr/share/elasticsearch/place-index.json
      - ./init-index.sh:/usr/share/elasticsearch/init-index.sh
    ports:
      - "9200:9200"
    command: >
      /bin/bash -c "
      chmod +x /usr/share/elasticsearch/init-index.sh &&
      /usr/share/elasticsearch/init-index.sh &
      exec /usr/local/bin/docker-entrypoint.sh
      "

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

volumes:
  esdata:
    driver: local