name: Deploy on Push

on:
  push:
    branches:
      - develop

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      FE_changed: ${{ steps.frontend_changes.outputs.changed }}
      BE_changed: ${{ steps.backend_changes.outputs.changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check for frontend changes
        id: frontend_changes
        run: |
          if git diff --name-only HEAD~1 | grep -q "^frontend/"; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

      - name: Check for backend changes
        id: backend_changes
        run: |
          if git diff --name-only HEAD~1 | grep -q "^backend/"; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

  deploy-be:
    needs: check_changes
    name: Deploy Backend if changed
    if: needs.check_changes.outputs.BE_changed == 'true'
    uses: ./.github/workflows/deploy-be.yml
    secrets: inherit

  deploy-fe:
    needs: check_changes
    name: Deploy Frontend if changed
    if: needs.check_changes.outputs.FE_changed == 'true'
    uses: ./.github/workflows/deploy-fe.yml
    secrets: inherit
