name: Deploy Frontend

on:
  push:
    branches:
      - develop
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build React App
        env:
          VITE_AXIOS_PROD_BASE_URL: ${{ secrets.VITE_AXIOS_PROD_BASE_URL }}
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
          VITE_GOOGLE_MAPS_ID: ${{ secrets.VITE_GOOGLE_MAPS_ID }}
          VITE_GOOGLE_AUTH_URL: ${{ secrets.VITE_GOOGLE_AUTH_URL }}
          VITE_TEST_ACCESS_TOKEN: ${{ secrets.VITE_TEST_ACCESS_TOKEN }}
        run: |
          cd ${{ github.workspace }}/frontend
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy to Nginx Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_SERVER_HOST }}
          username: ${{ secrets.NCP_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/dist/*"
          target: "/usr/share/nginx/html/"
