name: Deploy Frontend

on:
  push:
    branches:
      - develop
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build React App
        run: |
          cd ${{ github.workspace }}/frontend
          yarn install
          yarn build

      - name: Deploy to Nginx Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_SERVER_HOST }}
          username: ${{ secrets.NCP_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/dist/*"
          target: "/usr/share/nginx/html/"
